scripts: "workflow/scripts/"
output: "results/"
logs: "logs/"
interactive_clean: True

renv_loc: <path/to/user/R/library>

anndata:
    atac: <path/to/ATAC/AnnData/here>
    rna: <path/to/RNA/AnnData/here>
    sc_atac: <path/to/singlecell/ATAC/AnnData/here>

peaks:
    width: 150
    genome: "hg38"
    meme_file: "data/cis-bp-tf-information.meme"

ins_chip:
    verbose: False
    min_chip: 0.15
    min_peak_hits: 30

gene_peak_corr_config:
    n_jobs: 1
    test_set: ""
    n_genes: 20

gene_peak_corr_cutoffs:
    min_corr: 0.0
    max_pval: 0.1
    min_peaks: 2

acc_metric:
    ld_embedding: "X_svd"
    read_length: 147
    op_nbors: 3
    open_peak_pval: 0.01
