scripts: "workflow/scripts/"
output: # <Output directory here> 
logs: "logs/"
interactive_clean: True

renv_loc: # <path/to/user/R/library>

anndata:
    atac: # <path/to/SEACell/ATAC/AnnData/here>
    rna: # <path/to/SEACell/RNA/AnnData/here>
    sc_atac:  # <path/to/Single-cel/ATAC/AnnData/here>
    sc_rna: # <path/to/Single-cel/RNA/AnnData/here>
    # documenting what label was used to create the SEACells AnnData - also used for differential accessibility
    SEACell_label: "SEACell"
peaks:
    width: 150
    genome: # Specify genome here
    meme_file: "data/cis-bp-tf-information.meme"

ins_chip:
    # set verbose to "--verbose" for True
    verbose: ""
    min_chip_score: 0.15
    min_peak_hits: 30

gene_peak_corr_config:
    # set test_set to "--test_set" for True
    n_jobs: 1
    test_set: ""
    n_genes: 20

gene_peak_corr_cutoffs:
    min_corr: 0.0
    max_pval: 0.1
    min_peaks: 2
    
diff_acc:
    to_compare: # Specify comparisons here Eg:"EryPre1,proB/Mono,proB/EryPre1,HSC/Mono,HSC"
    cell_type_obs: # Specify obs which contains the cell type information .Eg: "celltype"
    
peak_selection:
    target:  # List of cell-types for the target lineage. Eg: ["Bcells","proB"]
    start: # Stem cell type. Eg: "HSC"
    reference: # Dictionary of reference/other cell types for comparison. Eg listed below
         Ery: "EryPre1"
         Mono: "Mono"
    min_logFC: 0
    max_logFC: 0.25
    
