scripts: "workflow/scripts/"
output: "results/"
logs: "logs/"

renv_loc: <path/to/user/R/library>

anndata:
    atac: <path/to/ATAC/AnnData/here>
    rna: <path/to/RNA/AnnData/here>
    SEACell_label: "SEACell" 

peaks:
    width: 150
    genome: "hg38"
    meme_file: "/fh/fast/setty_m/grp/motif_databases/CIS-BP_2.00/Homo_sapiens.meme"

gene_peak_corr_config:
    n_jobs: 1
    test_set: ""
    n_genes: 20

gene_peak_corr_cutoffs:
    min_corr: 0.0
    max_pval: 0.1
    min_peaks: 2

acc_metric:
    ld_embedding: "X_svd"
    read_length: 147
    op_nbors: 3
    open_peak_pval: 0.01
