scripts: "workflow/scripts/"
output: "results/"
logs: "logs/"
interactive_clean: True

renv_loc: <path/to/user/R/library>

anndata:
    atac: <path/to/SEACell/ATAC/AnnData/here>
    rna: <path/to/SEACell/RNA/AnnData/here>
    sc_atac: <path/to/singlecell/ATAC/AnnData/here>
    sc_ad: <path/to/singlecell/plotting/AnnData/here>
    # documenting what label was used to create the SEACells AnnData
    SEACell_label: "SEACell"    
peaks:
    width: 150
    genome: "hg38"
    meme_file: "data/cis-bp-tf-information.meme"

ins_chip:
    # set verbose to "--verbose" for True
    verbose: ""
    min_chip_score: 0.15
    min_peak_hits: 30

plot_chromvar:
    vmax: 3
    tf_list: <space-separated list of TFs to plot, no quotations>
    obs_annos: <space-separated list of .obs annotations to plot, no quotations>
    embedding: "umap"

gene_peak_corr_config:
    # set test_set to "--test_set" for True
    n_jobs: 1
    test_set: ""
    n_genes: 20

gene_peak_corr_cutoffs:
    min_corr: 0.0
    max_pval: 0.1
    min_peaks: 2

acc_metric:
    ld_embedding: "X_svd"
    read_length: 147
    op_nbors: 3
    open_peak_pval: 0.01
