scripts: "workflow/scripts/"
output: "results/"
logs: "logs/"
renv_loc: <path/to/user/R/library>

atac: <path/to/ATAC/AnnData/here>
rna: <path/to/RNA/AnnData/here>
SEACell_label: "SEACell" 

in_meme: "/fh/fast/setty_m/grp/motif_databases/CIS-BP_2.00/Homo_sapiens.meme"

width: 150
genome: "hg38"
n_jobs: 1

test_set: ""
n_genes: 20

min_corr: 0.0
max_pval: 0.1
min_peaks: 2

ld_embedding: "X_svd"
read_length: 147
op_nbors: 3
open_peak_pval: 0.01
