scripts: "workflow/scripts/"
output: "results/"
logs: "logs/"

atac: ""
rna: ""
in_meme: "/fh/fast/setty_m/grp/motif_databases/CIS-BP_2.00/Homo_sapiens.meme"

width: 150
genome: "hg38"
n_jobs: "1"

min_corr: 0.0
max_pval: 0.1
min_peaks: 2
