scripts: "workflow/scripts/"
output: "/fh/fast/setty_m/user/cjordan2/repositories/chromatin-dynamics/data/retina/"
logs: "/fh/fast/setty_m/user/cjordan2/repositories/chromatin-dynamics/data/retina/logs"
interactive_clean: True

renv_loc: "/home/cjordan2/R/x86_64-pc-linux-gnu-library/4.1.0" 
mudata:
    meta: "/fh/fast/setty_m/user/cjordan2/repositories/chromatin-dynamics/data/retina/retina_D59_meta_multiome.h5mu"
    sc: "/fh/fast/setty_m/user/cjordan2/repositories/chromatin-dynamics/data/retina/retina_D59_multiome.h5mu"

anndata:
    atac: "/fh/fast/setty_m/user/cjordan2/repositories/chromatin-dynamics/data/retina/retina_D59_meta_multiome.h5mu/ATAC"
    rna: "/fh/fast/setty_m/user/cjordan2/repositories/chromatin-dynamics/data/retina/retina_D59_meta_multiome.h5mu/RNA"
    sc_atac: "/fh/fast/setty_m/user/cjordan2/repositories/chromatin-dynamics/data/retina/retina_D59_multiome.h5mu/ATAC"
    sc_rna: "/fh/fast/setty_m/user/cjordan2/repositories/chromatin-dynamics/data/retina/retina_D59_multiome.h5mu/RNA"
    # documenting what label was used to create the SEACells AnnData - also used for differential accessibility
    SEACell_label: "SEACell"
peaks:
    width: 150
    genome: 'hg38'
    meme_file: "data/cis-bp-tf-information.meme"

ins_chip:
    # set verbose to "--verbose" for True
    verbose: ""
    min_chip_score: 0.15
    min_peak_hits: 30
    n_frags_label: 'nCount.ATAC'

gene_peak_corr_config:
    # set test_set to "--test_set" for True
    n_jobs: 1
    test_set: ""
    n_genes: 20

gene_peak_corr_cutoffs:
    min_corr: 0.0
    max_pval: 0.1
    min_peaks: 2
    
peak_selection:
    cell_type_obs: 'celltype'
    start: 'MPC' # stem cell type 
    reference: # Dictionary of lineages: reference cell types
        RGC : 'RGC_late'
        HRZ : "HRZ"
        CON : 'CON'
    min_logFC: 0
    max_logFC: 0.25
    