scripts: "workflow/scripts/"
output: "test-results/"
logs: "test-logs/"
interactive_clean: True

renv_loc: "/home/cjordan2/R/x86_64-pc-linux-gnu-library/4.1.0" # <path/to/user/R/library>

anndata:
    atac: "/fh/fast/setty_m/user/cjordan2/repositories/geneTF/data/test_atac_meta_ad.h5ad"  #<<path/to/SEACell/ATAC/AnnData/here>
    rna: "/fh/fast/setty_m/user/cjordan2/repositories/geneTF/data/test_rna_meta_ad.h5ad" #<path/to/SEACell/RNA/AnnData/here>
    sc_atac: "/fh/fast/setty_m/user/cjordan2/repositories/geneTF/data/test_atac_ad.h5ad" 
    sc_rna: "/fh/fast/setty_m/user/cjordan2/repositories/geneTF/data/test_rna_ad.h5ad" 
    # documenting what label was used to create the SEACells AnnData - also used for differential accessibility
    SEACell_label: "SEACell"
peaks:
    width: 150
    genome: "hg38"
    meme_file: "data/cis-bp-tf-information.meme"

ins_chip:
    # set verbose to "--verbose" for True
    verbose: ""
    min_chip_score: 0.15
    min_peak_hits: 30

gene_peak_corr_config:
    # set test_set to "--test_set" for True
    n_jobs: 1
    test_set: ""
    n_genes: 20

gene_peak_corr_cutoffs:
    min_corr: 0.0
    max_pval: 0.1
    min_peaks: 2
    
diff_acc:
    to_compare: "EryPre1,proB/Mono,proB/EryPre1,HSC/Mono,HSC"
    group_variable: "celltype_combined"
    
peak_selection:
    target: ["Bcells","proB"]
    start: "HSC"
    reference: 
         Ery: "EryPre1"
         Mono: "Mono"
    min_logFC: -0.25
    max_logFC: 0.25
    
